version: "3.6"
services:
  app:
    container_name: app
    build: .
    command: npm start
    ports:
      - "3333:3000"
    volumes:
      - ./wp-plugin-erp:/usr/app
    links:
      - sqlserver
    env_file: .env
    restart: on-failure
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1436:1433"
    env_file: .env
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 30s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Testing1122 -d master -Q 'CREATE DATABASE SiteEstacoes' && sleep infinity"

